spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guide
    username: subasi
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect