spring:
  security:
    user:
      name: subasi
      password: 123456
  datasource:
    url: jdbc:postgresql://localhost:5432/guide
    username: subasi
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 200000
      connectionTimeout: 30000
      connection-test-query: SELECT 1
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: create
      hibernate:
        generate_statistics: false
        jdbc:
          fetch_size: 1000
          lob.non_contextual_creation: true
        ddl-auto: update
        hbm2dll:
          create_namespaces: true
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: guide
        show_sql: true
        format_sql: true
        connection:
          url: jdbc:postgresql://localhost:5432/guide
          password: 123456
          username: subasi
          driver_class: org.postgresql.Driver


#  liquibase:
#    enabled: true
#    default-schema: guide
#    drop-first: false
#    url: jdbc:postgresql://localhost:5432/guide
#    user: subasi
#    password: 123456
#    driver-class-name: org.postgresql.Driver
